# Generated by Django 5.1.3 on 2024-11-17 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='precio',
        ),
    ]
