# Generated by Django 5.1.3 on 2024-11-17 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_remove_curso_fecha_inicio_remove_curso_precio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['titulo'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.CreateModel(
            name='CursoOfertado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.CharField(max_length=250)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('sede', models.PositiveIntegerField(choices=[(1, 'Plantel Centro'), (2, 'Plantel Tenosique')])),
                ('capacidad', models.PositiveSmallIntegerField(default=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Curso Ofertado',
                'verbose_name_plural': 'Cursos Ofertados',
                'db_table': 'curso_ofertado',
            },
        ),
    ]
