# Generated by Django 5.1.3 on 2024-11-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_alter_curso_options_cursoofertado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatusCursoOfertado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estatus_curso_ofertado',
            },
        ),
    ]
