# Generated by Django 5.1.3 on 2024-11-17 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_estatuscursoofertado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursoofertado',
            name='estatus',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='cursos.estatuscursoofertado'),
            preserve_default=False,
        ),
    ]
