# Generated by Django 5.1.3 on 2024-11-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_cursoofertado_estatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'categoria_curso',
            },
        ),
    ]
