# Generated by Django 5.1.3 on 2024-11-19 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_curso_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatusPreinscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estatus_preinscripcion_curso',
            },
        ),
        migrations.CreateModel(
            name='PreinscripcionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprobante_domicilio', models.FileField(upload_to='archivos_incripcion')),
                ('curp', models.FileField(upload_to='archivos_incripcion')),
                ('identificacion_oficial', models.FileField(upload_to='archivos_incripcion')),
                ('comprobante_pago', models.FileField(blank=True, null=True, upload_to='archivos_incripcion')),
                ('comprobante_estudios', models.FileField(upload_to='archivos_incripcion')),
                ('acta_nacimiento', models.FileField(upload_to='archivos_incripcion')),
                ('nota', models.CharField(blank=True, max_length=250)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.estatuspreinscripcion')),
                ('prospecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preinscripcion',
                'verbose_name_plural': 'Preinscripciones',
                'db_table': 'preinscripcion_curso',
            },
        ),
    ]
