# Generated by Django 5.1.3 on 2024-11-19 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_estatuspreinscripcion_preinscripcioncurso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estatuspreinscripcion',
            options={'verbose_name': 'Estatus Preinscripcion Curso', 'verbose_name_plural': 'Estatus Preinscripciones Cursos'},
        ),
        migrations.AlterField(
            model_name='preinscripcioncurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.cursoofertado'),
        ),
    ]
